//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalsOfflineReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Discount
    {
        public int discno { get; set; }
        public Nullable<int> trn_Id { get; set; }
        public Nullable<int> disc_Id { get; set; }
        public string userid { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
