//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalsOfflineReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageAreaCoverage
    {
        public int p_areaNo { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> aID { get; set; }
        public Nullable<bool> is_extended { get; set; }
        public Nullable<decimal> ext_amount { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Package Package { get; set; }
    }
}
