//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalsOfflineReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string payNo { get; set; }
        public Nullable<int> trn_Id { get; set; }
        public Nullable<System.DateTime> dateofPayment { get; set; }
        public string particular { get; set; }
        public Nullable<int> payType { get; set; }
        public Nullable<decimal> amtPay { get; set; }
        public string pay_means { get; set; }
        public string checkNo { get; set; }
        public string notes { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
