//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalsOfflineReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Refund()
        {
            this.RefundEntries = new HashSet<RefundEntry>();
        }
    
        public long Rf_id { get; set; }
        public Nullable<System.DateTime> rfDate { get; set; }
        public Nullable<int> trn_Id { get; set; }
        public string rf_Reason { get; set; }
        public Nullable<decimal> rf_Amount { get; set; }
        public Nullable<decimal> rfDeduction { get; set; }
        public Nullable<decimal> rfNetAmount { get; set; }
        public Nullable<int> rf_Stat { get; set; }
    
        public virtual Booking Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundEntry> RefundEntries { get; set; }
    }
}
