//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalsOfflineReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddonDetail
    {
        public int addonId { get; set; }
        public Nullable<int> addoncatId { get; set; }
        public string addondescription { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual AddonCategory AddonCategory { get; set; }
    }
}
