//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalsOfflineReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringDiscount
    {
        public int id { get; set; }
        public Nullable<int> DiscPaxMin { get; set; }
        public Nullable<int> DiscPaxMax { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
