//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalsOfflineReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Book_Menus = new HashSet<Book_Menus>();
        }
    
        public string menuid { get; set; }
        public Nullable<int> CourserId { get; set; }
        public string menu_name { get; set; }
        public Nullable<int> deptId { get; set; }
        public string note { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Menus> Book_Menus { get; set; }
        public virtual CourseCategory CourseCategory { get; set; }
        public virtual Department Department { get; set; }
    }
}
