//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalsOfflineReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagesRangeBelowMin
    {
        public int no { get; set; }
        public Nullable<int> pMin { get; set; }
        public Nullable<int> pMax { get; set; }
        public Nullable<decimal> Amt_added { get; set; }
    }
}
