//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalsOfflineReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int resId { get; set; }
        public int c_Id { get; set; }
        public System.DateTime resDate { get; set; }
        public int noofPax { get; set; }
        public string occasion { get; set; }
        public bool reserveStat { get; set; }
        public string eventVenue { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
